### PR TITLE
Add support for Beyond Compare 5.

### PR DESCRIPTION
**Pull request by alerosmile**

### CODE REVIEW

**Comment by alerosmile** [comment]
Closes #4.

**Comment by ContextQuickie** [comment]
Hi @alerosmile ,
thanks for the contribution. I was not aware that the plugin is still in use.
I'll have to check if I can restore my build enviroment to create a new release.
Best Regards 
Roland

**Comment by RolandoMagico** [comment]
Hello @alerosmile ,
did you test the changes? Currently, Beyond Compare 5 seems to work only on files, but not on folders.
Tested with:
- Eclipse IDE for Eclipse Committers Version: Neon.3 Release (4.6.3)
- Eclipse IDE for C/C++ Developers (includes Incubating components) Version: 2024-09 (4.33.0)

both on a Windows 10 machine.

**Comment by alerosmile** [comment]
@RolandoMagico  Sure, I'm using this plugin daily! It's one of my favorites.

To be honest, I've tested the file part only. I rarely use it on folders. But you are right, it doesn't work on folders. This is because BC5 folder compare is registered under `HKCR\Directory\Background\shellex\ContextMenuHandlers` whereas BC4 is registered under `HKCR\Folder\shellex\ContextMenuHandlers`. You have to add this [here](https://github.com/RolandoMagico/ExplorerContextMenu/blob/ec9fbe0f7cb4bf1098932505658a2ae07f03b7a5/Source/Common/ExplorerContextMenu.cpp#L125). Do you want me to create a PR for this?

And there is another Problem: [std::unique](https://github.com/RolandoMagico/ExplorerContextMenu/blob/ec9fbe0f7cb4bf1098932505658a2ae07f03b7a5/Source/Common/ExplorerContextMenu.cpp#L136) removes **consecutive** duplicates only. All duplicates should be removed here, I guess.

**Comment by RolandoMagico** [comment]
@alerosmile : Thanks for the analysis. Would be greate if you have time to crete a PR. Otherwise I'll have a look at it on the weekend

**Comment by alerosmile** [comment]
@RolandoMagico I've created a PR: https://github.com/RolandoMagico/ExplorerContextMenu/pull/1

**Pull request merged**
